# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "moonfly"

[c]
style = "green"

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"

[directory]
truncation_length = 4
style = "fern"

[git_branch]
style = "lavender"

[package]
style = "orange"

[perl]
style = "green"

[swift]
style = "red"

[terraform]
style = "purple"

[palettes.moonfly]
fern = "#87d787"
lavender = "#adadf3"
orange = "#f09479"
red = "#f07496"

[nodejs]
format = '[$symbol$version](bold green) '
